### ISSUE TITLE
How to get callbacks if desired instead of coroutines?

### ISSUE THREAD

**Issue by rbresalier** [Tradias/asio-grpc#10]
I was wondering if it is possible to use this library to get callbacks if desired instead of coroutines?

I understand coroutines are more developer friendly, but sometimes we may want callbacks instead.

Examples:
   a callback on server when server receives an rpc request
   a callback on client when client receives a response to a request

Are there existing APIs to do this? If so how?

**Comment by Tradias** [comment]
Yes see here: https://github.com/Tradias/asio-grpc#different-completion-tokens

**Comment by rbresalier** [comment]
Thanks!
