### ISSUE TITLE
simple program stuck

### ISSUE THREAD

**Issue by JaydenFish** [Tradias/asio-grpc#102]
```
#define AGRPC_BOOST_ASIO
#define AGRPC_UNIFEX
#include <agrpc/asio_grpc.hpp>

int main(int argc, char *argv[], char *envp[])
{
    agrpc::GrpcContext grpc_context;
    return 0;
}
```
run with `g++ -Iinclude -lgrpc++ -lgrpc_unsecure -labsl_synchronization -o test_agrpc main/test_agrpc.cpp && ./test_agrpc`, it stuck.
but run with `g++ -Iinclude -lgrpc++ -labsl_synchronization -o test_agrpc main/test_agrpc.cpp && ./test_agrpc` , it is ok.
looks have something wrong with `-lgrpc_unsecure`
my enviroment is gcc 14.1.1  fedora 41 @agrpc v3.1.0@6cee405b

**Comment by Tradias** [comment]
You may not mix `grpc++` and `grpc_unsecure` within one application. This is a limitation of gRPC. In other words, remove `-lgrpc++` and `-lgrpc_unsecure` from the first command line, add only `-lgrpc++_unsecure`.

 See https://github.com/Tradias/asio-grpc/issues/61

And https://github.com/grpc/grpc/issues/24422#issuecomment-843326936

**Comment by Tradias** [comment]
Btw if you prefer to set things up with CMake, there is an example on how to consume system installed gRPC with pkgconfig from CMake: https://github.com/Tradias/asio-grpc/issues/60#issuecomment-1365957537
