### ISSUE TITLE
Failed to compile the latest version with c++17

### ISSUE THREAD

**Issue by khanhha** [Tradias/asio-grpc#11]
Hi, we have tried to install asio-grpc 1.3.1 using https://vcpkg.info. Building it works but importing the lib into our c++14 project caused compiling problem. The header file "version" does not exist in c++14. 
```c++
#include <version>
```
we are using msvc in windows 10

We cannot easily upgrade our big project with many libs to c++20. We would like to ask if there is a way to install asio-grpc 1.21 using vcpkg?
Thanks

**Comment by khanhha** [comment]
solutions
- update the version field inside /vcpkg/ports/asio-grpc/vcpkg.json to 1.1.2
- install asio-vcpkg using the command: ./vcpkg install asio-grpc[boost-container]:x64-linux
- install is successfully

**Comment by Tradias** [comment]
I am assuming you meant C++17 in both cases: issue title and description.

You are right, technically the `<version>` is part of C++20, but most compilers are providing it regardless of the specified C++ standard on the command line. MSVC has had it for [quite a while](https://github.com/microsoft/STL/blob/main/stl/inc/version), I believe it was already part of [VS 2019 16.5](https://github.com/microsoft/STL/wiki/Changelog#vs-2019-165). Are you using a much older version?  If yes, then an update should solve the problem even when compiling in C++17 mode.

In fact this version: MSVC 19.29.30137.0 (Visual Studio 16 2019) is tested by [github actions](https://github.com/Tradias/asio-grpc/runs/4278178549?check_suite_focus=true) and works fine. I am personally use MSVC when developing asio-grpc and never had this issue.

Nonetheless, I will make sure that the `<version>` will not be included when compiling in pre C++20 mode.
