### ISSUE TITLE
compiling problem with versions installed by vcpkg

### ISSUE THREAD

**Issue by khanhha** [Tradias/asio-grpc#12]
Hi, thanks for creating a wonderful framework. It has made my life much easier.

I have used your framework for a few months and now I need to set up our project on a new machine. The installation is successful with the following command
```
./vcpkg install asio-grpc[boost-container]:x64-linux
```
However, when I compile my project, I got the following errors.
![image](https://user-images.githubusercontent.com/2276264/145624991-1dce4509-f026-41b5-9fd3-a20b75913f80.png)
![image](https://user-images.githubusercontent.com/2276264/145625366-00c5fe9d-ddd4-4cc6-a261-f55146503ba7.png)
![image](https://user-images.githubusercontent.com/2276264/145629496-3fbb41ed-1012-4075-98c2-99987266666d.png)
![image](https://user-images.githubusercontent.com/2276264/145630531-80440701-676c-4f2b-b698-6b89013832d7.png)

Do you have any idea why does this error happen?

I look forward to hearing from you soon.

Thanks

**Comment by Tradias** [comment]
The solution is to link with `asio-grpc::asio-grpc` as described in the [Usage](https://github.com/Tradias/asio-grpc#usage) (expand the `Using vcpkg` section):

```cmake
find_package(asio-grpc)
target_link_libraries(your_app PRIVATE asio-grpc::asio-grpc)
```

You also need to have your desired backend installed. For `asio-grpc::asio-grpc` that would be Boost.Asio which can be installed with:

```shell
vcpkg install boost-asio:x64-linux
```

Any suggestions on how to improve that workflow are welcome. I have already added this message when installing asio-grpc with vcpkg. E.g. after running `vcpkg install asio-grpc[boost-container]:x64-windows-static` on my machine:

```
Installing package asio-grpc[boost-container,core]:x64-windows-static...
Elapsed time for package asio-grpc:x64-windows-static: 1.972 s

Total elapsed time: 12.93 min

The package asio-grpc can be used with different backends.

    find_package(asio-grpc CONFIG REQUIRED)

The Boost.Asio backend. Install "boost-asio" and link with:

    target_link_libraries(main PRIVATE asio-grpc::asio-grpc)

The standalone Asio backend. Install "asio" and link with:

    target_link_libraries(main PRIVATE asio-grpc::asio-grpc-standalone-asio)

The libunifex backend. Install "libunifex" and link with:

    target_link_libraries(main PRIVATE asio-grpc::asio-grpc-unifex)
                                                                                                                                                                                                                                                                                                                                                                                                                              
```

Additionally, I will add an `#error` statement to the code. In the next release of the library the compile error message will then look like this in case `asio-grpc::asio-grpc` has not been linked with:

```
[build] test\build-test-debug\vcpkg_installed\x64-windows-static\include\agrpc/detail/config.hpp(73): fatal error C1189: #error:  asio-grpc backend macro is not defined. Did you forget to link with `asio-grpc::asio-grpc` in your CMake file?
```

On another note, I can recommend using the [vcpkg manifest mode](https://vcpkg.io/en/docs/users/manifests.html) instead of the manual install: Create a [vcpkg.json](https://github.com/Tradias/asio-grpc/blob/master/vcpkg.json) file in your project root and configure CMake with `-DCMAKE_TOOLCHAIN_FILE=<vcpkg root>/scripts/buildsystems/vcpkg.cmake`. In your case the vcpkg.json might look like this:

```json
{
    "name": "test",
    "version-string": "0.1.0",
    "dependencies": [
        {
            "name": "asio-grpc",
            "features": [
                "boost-container"
            ]
        },
        "boost-asio"
    ]
}
```

I am also curious on how you use asio-grpc. Did you integrate it with Qt in some way? What are your pain points? Anything you would like to see changed or improved in the library?

**Comment by Tradias** [comment]
@khanhha did you have time to try my suggested solution?

**Comment by khanhha** [comment]
@Tradias Sorry for the late response. 

- I have come back to the task last week and managed to compile all the code in Windows.

I have to include this file in the beginning of every agrpc-related header files to get around two more compiling problems
```c++
#ifndef WIN_INCLUDE_FIXES
#define WIN_INCLUDE_FIXES
#ifdef _WIN32
// include this file in the top of all files which involves grpc and boost asio to fix the following compiling problem.
// fix Winsock is not included, maybe due to boost::asio
// set the proper SDK version before including boost::asio
#include <SDKDDKVer.h> 
// note boost/ASIO includes Windows.h.
#include<boost/asio.hpp>

//for fixing a weird compiling error with Window SDK
//https://github.com/microsoft/vcpkg/issues/9353
#undef FAR

#else // _WIN32
#include <boost/asio.hpp>
#endif //_WIN32
#endif 
```

- Our project is a distributed motion capture system that uses your framework to stream data back and forward between multiple machines. Previously I have tried to build a bidirectional streaming framework from scratch using only gRPC. However, it's not maintainable and error-prone due to a large amount of service and streaming code. As a developer whose experienced in both grpc and asio-grpc, I can tell that your framework is a real a game-changer for writing grpc code in C++. It has made my life much easier.

**Comment by Tradias** [comment]
Great, I am glad to hear that my library is helping. If you have time, can you try to update to asio-grpc v1.3.1? Neither of the two compiling problems that you mentioned directly affect asio-grpc, I therefore expect that you should not run into trouble with the update.

On another note, do you mind if I quote you in the README in a section titled "What users of asio-grpc are saying", to increase the other users' confidence in the library?

I also want to present two more options on how to could solve issue 1. Not saying that any one is better, they all have their advantages and disadvantages:

Option 1: Add a preprocessor define for the Windows version you are targeting. E.g. for [Windows 10](https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170):

```cmake
target_compile_definition(my_app PRIVATE $<$<CXX_COMPILER_ID:MSVC>:_WIN32_WINNT=0x0A00>)
```
As seen here:
https://github.com/Tradias/asio-grpc/blob/master/cmake/AsioGrpcCompileOptions.cmake#L60-L61

Option 2: Add a precompiled header. In CMakeLists.txt:

```cmake
target_precompile_headers(my_app PRIVATE "precompiledHeader.h")
```

where `precompiledHeader.h` is:

```c++
#ifdef _WIN32
#include <SDKDDKVer.h>
#endif
// Include any other frequently used header like <string> to speed up compile times
#include <agrpc/asioGrpc.hpp>
```

**Comment by khanhha** [comment]
Hi Tradias

Thank you very much for your suggestion, it will absolutely simplify the code by a great deal.

Please feel free to use my feedbakc, I am glad that it will help spread your framework to others who are also struggling with grpc c++ code. 

Regarding your suggestion using version 1.3.0, I have tried 1.3.0 a few weeks ago but it produces a lot of weird errors that I don't have enough to dig in now. The version 1.1.2 is still good enough for, but I will absolutely let you know if I have any success in using version 1.3.1.

Wish you all the best. Stay healthy to keep building this great framework. 
Best
Khanh

**Comment by Tradias** [comment]
I am closing the issue for now. If you have more issues or questions then do not hesitate to open another ticket.
