### ISSUE TITLE
Question: is it possible to implement a server to client request, using a bidirectional-streaming channel and exposed as a standard C++ class/interface?

### ISSUE THREAD

**Issue by OleStauning** [Tradias/asio-grpc#13]
Hi,

Thank you for writing this library. 

I'm currently trying trying to use asio-grpc for implementing a service that, as a part of a request, can call back to a connected client to get additional data - dependency injection style. This dependency injection channel is a long-living bidirectional streaming grpc call. My problem is that the server-logic is calling into a normal pure virtual class (interface) for requesting these values. AFAIK this rules out using co_await, co_return since this would imply my interface should return a coroutine. So I'm trying to figure out if I can implement such interface by using co_yield, where the consumer of the values does not need to be a coroutine.

The server-logic is being triggered by another async grpc call, but the server-logic itself is not async.

I hope someone is able to help me to figure out if and how this is possible. Let me know if my description is not clear enough.

Best regards

**Comment by Tradias** [comment]
I assume that the interface cannot not be changed and looks something like this:

```cpp
class Interface {
  virtual Data get_additional_data(Request) = 0;
};
```

where `Request` is the request that the service you are trying to implement has received from its clients and `Data` the information that the service wants to get from the connected client in the back.

I also assume that the connected client takes `Request`, puts some marker on it and writes it into the bidirectional stream. Then reads from the stream until the corresponding `Data` becomes available.

I assume that It is possible that there are multiple outstanding calls to `get_additional_data`. If not, then the client might as well be synchronous.

I am right that you would therefore want to implement something like:

```cpp
class ConnectedClient : Interface {
  Data get_additional_data(Request request) override {
    auto marker = create_marker();
    MarkedRequest m{request, marker};
    // write m to the bidirectional stream, potentially interleaved with other reads on the stream
    Data data;
    // read from bidirectional stream until Data becomes available
    return data;
  }
};
```

**Comment by OleStauning** [comment]
Yes, this is exactly the situation. 

The interface is as you describe and cannot be changed. Since the async sending of a request and reading the reply is implemented by coroutine, using co_await ( agrpc::write && agrpc::read ), I need some kind of adaptor that translates calls to the synchronous get_additional_method into some interaction with a coroutine and then resumes the synchronous call when Data is ready to be returned. The only way I can see how this should be possible is by using co_yield to return the Data from the coroutine, but I cannot figure out how to implement such an adaptor. 

The thread that executes the get_additional_data method is the (one and only) asio service thread since the execution of the synchronous C++ code is being triggered by a grpc call. But I cannot see if/how this helps.

**Comment by Tradias** [comment]
I tried implementing it using `co_yield` and [asio::coro](https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/experimental__coro.html) but that did not turn out so well. Therefore went with [asio::channel](https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/experimental__basic_channel.html) instead.

https://github.com/Tradias/example-vcpkg-grpc/tree/asio-grpc-13

**Comment by OleStauning** [comment]
Thank you very much for your suggestion. I have not used the asio:channel before, but it seems to do the trick. I remember I had a similar problem before and it also seems to me to be a generic problem when integrating sync- and async code. So I think your solution can be used in many places.

Thanks!

**Comment by Tradias** [comment]
Great, I am glad to hear that I could help. If you have more questions or find a bug do not hesitate to create another issue.

**Comment by Tradias** [comment]
I put some more thought into your issue and realized that you said that:

>The thread that executes the get_additional_data method is the (one and only) asio service thread since the execution of the synchronous C++ code is being triggered by a grpc call.

Assuming that by `asio service thread` you mean the thread that runs the GrpcContext then the promise-based solution would deadlock. I have come up with a solution where the caller participates in the processing of the GrpcContext while waiting for its particular data to be ready. Please see https://github.com/Tradias/asio-grpc/issues/43 for more details.
