### ISSUE TITLE
Streaming reads incompatible with `||` awaitable operator

### ISSUE THREAD

**Issue by MrElectrify** [Tradias/asio-grpc#17]
Hello,
Firstly, great job adapting an un-ergonomic library to asio. I have been debugging a problem all day where combining a streaming `agrpc::read` with any other future with the awaitable `||` operator leads to the other futures not completing. It can be reproduced in the `streaming-client` bidirectional stream by changing the server such that it does not write to the stream, and awaiting on something like an alarm alongside the read/write calls on the client like below (after disabling the context timeout):

```cpp
// ... line 86
        std::variant<bool, std::tuple<bool, bool>> res =
            co_await (agrpc::wait(alarm, expiry) || 
                (agrpc::read(*reader_writer, response) && agrpc::write(*reader_writer, request)));
// ...
```

This will hang forever, beyond the expiry of the timer. Is this expected behavior? I understand there exist timeouts on client contexts, however as far as I can tell this leaves the stream in an unrecoverable state. Are reads "cancel safe" meaning they can be re-initiated without ill effects like [here](https://docs.rs/tokio/1.12.0/tokio/macro.select.html#cancellation-safety) in Rust, or is this just not possible? The use case is a recurring ping-type request being sent while simultaneously receiving data. The only solution I can think of would be to `co_spawn` another task to do this, but I would like to do it with these operators if at all possible.

Thanks

**Comment by Tradias** [comment]
asio-grpc provides a thin layer over gRPC. RPC step functions like `read` and `write` are therefore not cancel-safe as stated in [gRPC's documentation](https://grpc.github.io/grpc/cpp/classgrpc_1_1_client_async_reader_writer.html#a2f2c91734a7de5affdd427fb88ee6167) and also [asio-grpc's documentation](https://tradias.github.io/asio-grpc/structagrpc_1_1detail_1_1_read_fn.html#af737bdcfe170e27bc1c878bbe33163b8). We could potentially wrap them and make them safe, although we need to figure out what to do with the completion handler that were cancelled. In case of coroutines it might be ok to just abandon them, in a general case they should be completed with an error indicating cancellation. Let me know if you are interested in such a wrapper, then I will look into it.

In your case I would consider a `reader()`, `writer()` approach as shown in the [streaming-server example](https://github.com/Tradias/asio-grpc/blob/master/example/streaming-server.cpp#L120-L193). Adding an alarm to `channel.async_receive` might already do the trick: 

```cpp
co_await (channel.async_receive(...) || agrpc::wait(alarm expiry));
```

If you provide more context for your actual problem then I can also try to write a full example like I did for some of the other issues that have been reported to asio-grpc, see here: https://github.com/Tradias/example-vcpkg-grpc.

Regarding awaitable operators in asio. The first thing they do is to co_spawn the provided coroutines :). See [operator&&](https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/experimental/awaitable_operators.hpp#L75-L96) and [operator||](https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/experimental/awaitable_operators.hpp#L253-L287).

**Comment by MrElectrify** [comment]
That's the confusing bit for me, if you combine an alarm with a `agrpc::read` using `operator||` it ends up acting like an `operator&&` where it only returns when something is read regardless of the status of the `agrpc::wait` coro. If this is intended, it 's a very confusing intention.

The issue is I would not like to abandon the read if it has ill effects, the intention is to use the `wait` not as a timeout on the `read` but instead to send a sort of ping out every n seconds. In reality I am also able to send other messages than some ping but the ping is a solid n-second requirement. As you said this could be sent to another coroutine but it is best practice in languages like Rust to avoid concurrency issues in multi-threaded environments, and it's what I'm used to looping on something like `tokio::select`.

**Comment by Tradias** [comment]
I am sorry for the confusion, there was no intention at all. Asio requires asynchronous operations to support per-operation cancellation if they are to be used with features like `operator||`. gRPC does not provide cancellation for RPC step functions and asio-grpc should have documented that, which is done now (see e.g. [agrpc::finish](https://tradias.github.io/asio-grpc/structagrpc_1_1detail_1_1_finish_fn.html)).

In the meantime, I am working on opt-in cancellation safety. The first part is already done ([agrpc::CancelSafe](https://github.com/Tradias/asio-grpc/blob/master/src/agrpc/cancelSafe.hpp)) and I have been able to use it in a test for a read stream. I must say, writing code in such a style is quite cool, thank you for making me aware of it.

I wonder how you would expect the semantics to be. Currently I have something like:

```cpp
AsyncStream stream{grpc_context, agrpc::read, reader_writer, request};
while (true)
{
  // stream.next will automatically initiate the next read if none is pending.
  std::variant<bool, bool> result = co_await (agrpc::wait(alarm, deadline) || stream.next(asio::use_awaitable));
  if (0 == result.index()) // timer finished
  {
    // read continues to run in the background
  }
  else // read finished
  {
    // Alarm supports cancellation, so at this point it has been cancelled and awaited already
  }
}
// Should always cleanup the stream before exiting.
// Safe to call on a stream that has no read pending.
co_await stream.cleanup(asio::use_awaitable);
```

How should that look for write streams? The first call to "next" should probably not initiate any write and instead finish immediately.  Let's say there is some kind of "push" function to initiate the next write. What if a write is already pending, gRPC does not allow to initiate another write in that case. Should be request be buffered or leave it up to the user to ensure that any previous write has finished?

**Comment by MrElectrify** [comment]
That makes much more sense and describes the behavior I was seeing.

As for the read, I can't personally think of a better way to do it than you have here given the fact that the operation itself cannot be cancelled.

I personally think buffering outgoing messages is a little bit beyond the scope of the stream itself personally. If you create the AsyncStream for writing as you did for reading, I don't see how one would mistakenly push more data to send anyways.

**Comment by Tradias** [comment]
With [v1.6.0](https://github.com/Tradias/asio-grpc/releases/tag/v1.6.0) now released there is a [new utility class](https://tradias.github.io/asio-grpc/classagrpc_1_1_cancel_safe.html) that can be used to implement cancellation safe gRPC streams. Depending on the exact desired semantics of the stream that is rather easy, see: [grpcStream.hpp](https://github.com/Tradias/asio-grpc/blob/read-write-stream/src/agrpc/grpcStream.hpp).

I will close this issue in favor of https://github.com/Tradias/asio-grpc/issues/19 which tracks the progress of integrating a gRPC stream interface into asio-grpc.

**Comment by Tradias** [comment]
I highly doubt there will be data loss, otherwise the channel would be pretty useless. If you are send/receive data on the channel from multiple threads then you must use `concurrent_channel` though.

**Comment by nqf** [comment]
But rust tokio channel doesn' t seem to lose data,It is common to cooperate with select in rust
