### ISSUE TITLE
QNX support?

### ISSUE THREAD

**Issue by Tradias** [Tradias/asio-grpc#18]
@c6supper I have noticed that you started making [changes to asio-grpc to support QNX](https://github.com/c6supper/asio-grpc). Is there anything I can do to help?
I am not familiar with QNX, what are its limitations? Does it support C++17?

**Comment by c6supper** [comment]
> @c6supper I have noticed that you started making [changes to asio-grpc to support QNX](https://github.com/c6supper/asio-grpc). Is there anything I can do to help? I am not familiar with QNX, what are its limitations? Does it support C++17?

Hi Tradias,
Thanks for your attention.  At first I was just doing estimation on the IPC framework for automotive industry. When estimating the gRPC, I found your awesome project, so I decided to  port asio-grpc to  QNX7.0 (micro kernel, commercial OS, no source code), which compiler should be GCC5.4 (early C++17 version which makes me have no choice but to stick to c++14),  I did a try a pretty "nastied" way to eliminate building errors just want to estimate how much work is needed for my future porting job.  But the estimation is not so good, now I am focus on estimating another IPC framework(Fast-DDS).

**Comment by Tradias** [comment]
@c6supper I agree that porting asio-grpc to C++14 would be a lot of work, even for me. I see that [QNX7.1](https://www.qnx.com/developers/docs/7.1/index.html#com.qnx.doc.neutrino.utilities/topic/q/qcc.html) ships with GCC 8.3.0 which should work with asio-grpc right away. Maybe that could be an option for you.

In any case, thank you for considering asio-grpc. I hope that you find a suitable framework for your project :)

**Comment by Tradias** [comment]
Ok, I will also add GCC 8.3.0 to the CI system and fix any issues that might come up.

**Comment by Tradias** [comment]
Ubuntu only comes with GCC 8.4.0, I have added that to the CI system - all tests are passing 🎉 . Must use `ASIO_GRPC_USE_BOOST_CONTAINER`
