### ISSUE TITLE
Add support for systemd socket activation

### ISSUE THREAD

**Issue by eriksjolund** [Tradias/asio-grpc#37]
Feature request: Add support for systemd socket activation (LISTEN_FDS, LISTEN_FDNAMES)

The advantages are for instance

* [Native network performance over the socket-activated socket](https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md#native-network-performance-over-the-socket-activated-socket) when running rootless Podman. Network traffic is normally passed through the program __slirp4netns__ which comes with a performance penalty.  
* There is also a security advantage when running socket-activated containers with Podman. It's sometimes possible to run the container with __--network=none__. I wrote a blog about it https://www.redhat.com/sysadmin/socket-activation-podman

* The possibility to stop on inactivity and the starting when the next client connects. (The functionality to "stop on inactivity"  would need to be implemented in asio-grpc though)

* In the future it might be possible to run a socket-activated container with Podman as a systemd system service that makes use of (`User=`). Then it would be possible to use port numbers below 1024 without having to run the command `sudo sh -c "echo 0 > /proc/sys/net/ipv4/ip_unprivileged_port_start"`.  Unfortunately, I think there are some hurdles to get this working still.

**Comment by Tradias** [comment]
Hi, thanks for the request.

Note that asio-grpc interacts with gRPC on a high level. It only uses the grpcpp API which does not expose sockets in any way. I suggest that you move your issue to the gRPC core team, in particular to this issue: https://github.com/grpc/grpc/issues/19133. It also has a python example showing how one might hack socket activation into gRPC core. I am curious to try it out myself, but I am in no way familiar with podman and systemd.

**Comment by eriksjolund** [comment]
Hi, thanks for the feedback! I've now added a comment to the gRPC issue and I'm closing this issue.
