### ISSUE TITLE
share io_context example

### ISSUE THREAD

**Issue by assafcohen** [Tradias/asio-grpc#38]
Hi, 
first, I would like to thank you for a great library.
By looking at the example, it looks like that in order to share the asio::io_context for both  grpc and non grpc operations, we should replace all io_context with grpcContext, is that a right assumption?
thank you.

**Comment by Tradias** [comment]
Hi, thank you! I am glad you find the library useful.

There are essentially three ways of handling io_context+GrpcContext.

1. Let Asio implicitly create and manage the io_context.

```cpp
// The first time an Asio io-object that needs an io_context is created it will automatically construct
// an io_context and run it on a background thread. The lifetime of the io_context and thread are tied to the 
// grpc_context.
asio::steady_timer timer{grpc_context};
asio::co_spawn(grpc_context, [&]() -> asio::awaitable<void> {
  // Waiting for the timer will be handled by the hidden io_context.
  // Once it completes execution will automatically switch back to the grpc_context.
  co_await timer.async_wait();
}, asio::detached);

grpc_context.run();
```

2. Explicitly manage the io_context and grpc_context on one thread each. This might require additional synchronization code in your application to avoid race-conditions.

```cpp
asio::io_context io_context;
asio::steady_timer timer{io_context};

// Here we could co_spawn onto the grpc_context or io_context, whatever we prefer.
asio::co_spawn(grpc_context, [&]() -> asio::awaitable<void> {
  // Once the timer completes execution will automatically switch back to the grpc_context,
  // because we co_spawn'ed onto it.
  co_await timer.async_wait();

  // Whenever using asio-grpc RPC functions the grpc_context must be provided explicitly, unless
  // this coroutine was co_spawn'ed onto the grpc_context. But since it is error prone to keep track 
  // of that, I recommend to always bind the grpc_context, there is basically no runtime overhead.
  // Also, asio-grpc's RPC functions are thread-safe, so we can interact with them from the thread of 
  // the io_context.
  co_await agrpc::request(..., asio::bind_executor(grpc_context, asio::use_awaitable));

  // Here we would always be on the thread of the grpc_context, even if the coroutine was co_spawn'ed
  // onto the io_context, because asio-grpc behaves a bit differently than Asio due to the use of free functions.
}, asio::detached);

std::thread io_context_thread{[&] {
  io_context.run();
}};
grpc_context.run();
```

3. Use asio-grpc's [agrpc::run](https://tradias.github.io/asio-grpc/namespaceagrpc.html#ab52a5b6f6ce90d1bc9faa5baa96a39fa) function to run an explicitly managed io_context and grpc_context on the same thread. This is what the share-io-context examples show. We would work with the contexts just like in 2, use io_context for Asio's io-objects and grpc_context for asio-grpc RPCs (using bind_executor as needed).
