### ISSUE TITLE
Build with only the compiler (no cmake or any other build tools)

### ISSUE THREAD

**Issue by 4eUeP** [Tradias/asio-grpc#39]
Hi,  would you mind supporting the usage, which includes the sources by the compiler directly, not as a CMake package?

For example, let's say I have a `server.cpp` file, compiling with the following command without installing:

```
g++ -std=c++17 -fcoroutines \
  -DAGRPC_STANDALONE_ASIO \
  -DASIO_HAS_CO_AWAIT -DASIO_HAS_STD_COROUTINE -DASIO_HAS_CO_AWAIT \
  -Iasio-grpc/src -Iasio/asio/include -I</path/to/any/other/includes> \
  server.cpp \
  -lgrpc++ -lgpr -lgrpc++_reflection -lprotobuf -lpthread
```

---

The changes to support this seems little. The only problem is "memory_resource.hpp" not found since "memory_resource.hpp" is generated by CMake through `src/agrpc/detail/memory_resource.hpp.in`. A seemed reasonable way is to use a definition instead of a cmake variable.

```
// src/agrpc/detail/memory_resource.hpp.in
@ASIO_GRPC_MEMORY_RESOURCE_INDLUCES@

// =>

// src/agrpc/detail/memory_resource.hpp
#ifdef ASIO_GRPC_USE_BOOST_CONTAINER
namespace pmr = boost::container::pmr;
namespace container = boost::container;
#else
namespace pmr = std::pmr;
namespace container = std;
#endif
```

And then compile with `g++ -DASIO_GRPC_USE_BOOST_CONTAINER ...`

**Comment by Tradias** [comment]
Yes that should now work on master branch  by passing `-DAGRPC_USE_BOOST_CONTAINER` to the compiler.

Btw the reason the CMake generation is needed is due to https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#a-feature-may-replace-polyfills-with-aliases-provided-that-replacement-is-baked-into-the-installed-tree

**Comment by 4eUeP** [comment]
Thank you
