### ISSUE TITLE
Multi-threaded server and health check

### ISSUE THREAD

**Issue by nikkov** [Tradias/asio-grpc#50]
Hi,

I tried test example/multi-threaded-server with enabled DefaultHealthCheckService and found that after I set grpc::EnableDefaultHealthCheckService(true) before start server all handlers worked in only one thread. What could be causing this and how to fix it?

**Comment by Tradias** [comment]
I am unable to reproduce it, here is what I changed:

```diff
diff --git a/example/multi-threaded-server.cpp b/example/multi-threaded-server.cpp
index 7af18a3..2e87e97 100644
--- a/example/multi-threaded-server.cpp
+++ b/example/multi-threaded-server.cpp
@@ -16,6 +16,7 @@
 #include "server_shutdown.hpp"
 
 #include <agrpc/asio_grpc.hpp>
+#include <grpcpp/health_check_service_interface.h>
 #include <grpcpp/server.h>
 #include <grpcpp/server_builder.h>
 
@@ -47,16 +48,12 @@ void register_request_handler(agrpc::GrpcContext& grpc_context, helloworld::Gree
                 co_await agrpc::finish(writer, response, grpc::Status::OK);
 
                 // In this example we shut down the server after 20 requests
-                static std::atomic_int counter{};
-                if (19 == counter.fetch_add(1))
-                {
-                    shutdown.shutdown();
-                }
             }));
 }
 
 int main(int argc, const char** argv)
 {
+    grpc::EnableDefaultHealthCheckService(true);
     const auto port = argc >= 2 ? argv[1] : "50051";
     const auto host = std::string("0.0.0.0:") + port;
     const auto thread_count = std::thread::hardware_concurrency();
```

then I used [ghz](https://ghz.sh/) to test that it still uses multiple CPUs with the following config (ghz.json)

```json
{
    "proto": "example/proto/helloworld/helloworld.proto",
    "call": "helloworld.Greeter.SayHello",
    "total": 500000,
    "concurrency": 100,
    "insecure": true,
    "data": {
        "name": "Joe"
    },
    "max-duration": "20s",
    "host": "0.0.0.0:50051"
}
```

from the root of repository with the command line:

```shell
ghz --config ./ghz.json
```

And indeed it does. Needs a powerful machine though to actually exhaust the server with multiple CPUs.

**Comment by nikkov** [comment]
Is it may be depends from environment? I use Visual Studio 2022, Windows 10, gRPC 1.48 and asio-grpc 2.1.0 from vcpkg. 

I just added into handler delay and thread id output:
`std::cout << std::this_thread::get_id() << " read " << request.name() << std::endl;
std::this_thread::sleep_for(std::chrono::milliseconds(5000));
`
I used evans for manually grpc calls.
If I enable health check, handlers are run sequentially in same thread, example:
```
50380 read 1
50380 read 2
```

and without health check example:
```
66428 read 1
64372 read 2
```

**Comment by Tradias** [comment]
I am using the same environment now. I have a hard time getting evans to do concurrent request. I ended up creating a little script that performs three requests concurrently:

```sh
#!/bin/sh

echo '{ "name": "ktr" }' | "c:/temp/evans.exe" --proto example/proto/helloworld/helloworld.proto cli call helloworld.Greeter.SayHello &
echo '{ "name": "ktr" }' | "c:/temp/evans.exe" --proto example/proto/helloworld/helloworld.proto cli call helloworld.Greeter.SayHello &
echo '{ "name": "ktr" }' | "c:/temp/evans.exe" --proto example/proto/helloworld/helloworld.proto cli call helloworld.Greeter.SayHello
```
This can e.g. be run from Git Bash on Windows.

Then, with the `std::this_thread::sleep_for(std::chrono::milliseconds(5000));` I can see that it uses multiple thread. Without it, it seems to only use one thread. Maybe the requests are just processed too quickly.

In any case, updating to gRPC 1.49.0 and Boost 1.80 seems to help, regardless of `this_thread::sleep_for`.

**Comment by Tradias** [comment]
Btw, I personally use https://github.com/bloomrpc/bloomrpc to manually test gRPC servers.

**Comment by nikkov** [comment]
Thanks for bloomrpc, I forgot about it, it's really more simple for interactive testing.

I did the following exercises, updated to fresh vcpkg with grpc 1.49, Boost 1.80 and asio-grpc 2.2.0. Turning on the health check doesn't seem to change the behavior, but with 4 hardware threads only 3 requests are running in parallel. With thread_count = 3 I have only 2 really working threads.
I deliberately set a long delay of 5 seconds in order to manually run several queries and check the console output. I still don't understand the reason for this behavior yet.

**Comment by Tradias** [comment]
I see what you mean now. Internally gRPC has a background thread that accepts incoming requests. It then signals one of the CompletionQueues that called `agrpc::request` that a request is ready. The way in which gRPC selects a CompletionQueue, I do not know. But if it selects a queue that is currently in `this_thread::sleep` then the request will, of course, be stalled. 

`agrpc::repeatedly_request` internally invokes `agrpc::request` even before invoking the user provided request handler, which means it can easily lead to the situation described above.

How the health check services influences the selection mechanism, I also do not know. I ran [grpc_bench](https://github.com/Tradias/grpc_bench) to see the impact on performance and the results are surprising...

_Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, Linux, GCC 12.2.0, Boost 1.80.0, gRPC 1.50.0, asio-grpc v2.2.0, jemalloc 5.2.1
Request scenario: string_100B
2 CPUs_

## Without health check

| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
|-----------------------------|--------:|---------------:|---------------:|---------------:|---------------:|---------:|--------------:|
| cpp_grpc_mt                 |   89016 |        9.59 ms |       15.31 ms |       18.29 ms |       26.32 ms |  208.97% |     23.47 MiB |
| cpp_asio_grpc_unifex        |   88610 |        9.70 ms |       15.59 ms |       18.42 ms |       26.20 ms |  207.89% |     25.78 MiB |
| cpp_asio_grpc_callback      |   88423 |        9.66 ms |       15.19 ms |       18.23 ms |       25.87 ms |   210.8% |     28.28 MiB |
| cpp_asio_grpc_cpp20_coroutine |   85867 |       10.05 ms |       16.19 ms |       19.21 ms |       26.38 ms |  209.08% |     30.09 MiB |
| cpp_asio_grpc_io_context_coro |   75779 |       11.52 ms |       19.94 ms |       23.26 ms |       30.96 ms |  160.64% |      24.7 MiB |
| cpp_grpc_callback           |   66064 |       12.51 ms |       26.09 ms |       31.30 ms |       46.90 ms |  204.47% |     62.49 MiB |

## With health check

| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
|-----------------------------|--------:|---------------:|---------------:|---------------:|---------------:|---------:|--------------:|
| cpp_asio_grpc_cpp20_coroutine |   85827 |       10.05 ms |       16.48 ms |       19.62 ms |       27.15 ms |   207.4% |     30.51 MiB |
| cpp_asio_grpc_unifex        |   77914 |       11.14 ms |       18.60 ms |       22.11 ms |       29.76 ms |  213.89% |     50.85 MiB |
| cpp_grpc_mt                 |   76639 |       11.25 ms |       19.18 ms |       22.77 ms |       30.07 ms |  209.06% |     46.37 MiB |
| cpp_asio_grpc_callback      |   73223 |       11.91 ms |       21.12 ms |       24.87 ms |       35.39 ms |   208.7% |     48.42 MiB |
| cpp_grpc_callback           |   64597 |       12.82 ms |       26.87 ms |       32.25 ms |       49.90 ms |  207.58% |     61.23 MiB |
| cpp_asio_grpc_io_context_coro |   50906 |       17.69 ms |       36.90 ms |       47.88 ms |       67.47 ms |  159.13% |      45.4 MiB |

I will dig a bit deeper in the coming days.

**Comment by Tradias** [comment]
It seems that gRPC's [DefaultHealthCheckService](https://github.com/grpc/grpc/blob/master/src/cpp/server/health/default_health_check_service.cc) is implemented as a generic callback service. The server builder will therefore implicitly create a CallbackCompletionQueue - turning the resulting grpc::Server into a hybrid server. I suspect that ultimately leads to the performance degradation.

I will add a custom asynchronous version of the [HealthCheckServiceInterface](https://github.com/grpc/grpc/blob/master/include/grpcpp/health_check_service_interface.h) with the next release of asio-grpc (2.3.0). That should hopefully resolve the performance issue.

**Comment by Tradias** [comment]
The master branch now contains a [CompletionQueue-based implementation of the HealthCheckServiceInterface](https://tradias.github.io/asio-grpc/classagrpc_1_1_health_check_service.html), which no longer causes the performance degradation. It should also be a faster/more efficient health check implementation itself, compared to the gRPC default one.

_Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, Linux, GCC 12.2.0, Boost 1.80.0, gRPC 1.50.0, asio-grpc v2.2.0, jemalloc 5.2.1
Request scenario: string_100B_

# 2 CPUs

## Without health check

| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
|-----------------------------|--------:|---------------:|---------------:|---------------:|---------------:|---------:|--------------:|
| cpp_asio_grpc_unifex        |   89310 |        9.50 ms |       15.10 ms |       18.10 ms |       25.83 ms |  207.83% |     30.22 MiB |
| cpp_asio_grpc_callback      |   85832 |       10.01 ms |       15.86 ms |       18.92 ms |       26.29 ms |  208.08% |     24.08 MiB |
| cpp_asio_grpc_coroutine     |   77506 |       11.27 ms |       19.21 ms |       22.49 ms |       31.13 ms |   204.6% |     28.99 MiB |
| cpp_asio_grpc_io_context_coro |   75044 |       11.69 ms |       20.33 ms |       23.76 ms |       31.97 ms |  156.84% |     26.34 MiB |

## With health check

| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
|-----------------------------|--------:|---------------:|---------------:|---------------:|---------------:|---------:|--------------:|
| cpp_asio_grpc_unifex        |   86964 |        9.85 ms |       15.59 ms |       18.49 ms |       26.53 ms |  206.79% |     26.99 MiB |
| cpp_asio_grpc_callback      |   86908 |        9.88 ms |       15.71 ms |       18.69 ms |       26.59 ms |  209.69% |     25.64 MiB |
| cpp_asio_grpc_coroutine     |   77651 |       11.19 ms |       18.82 ms |       21.88 ms |       30.09 ms |  205.72% |     27.27 MiB |
| cpp_asio_grpc_io_context_coro |   73291 |       11.99 ms |       21.00 ms |       24.37 ms |       33.36 ms |  155.31% |     25.47 MiB |

**Comment by Tradias** [comment]
I am afraid that the same issue can also happen with other services, e.g. the server reflection is implemented as a synchronous service: https://github.com/grpc/grpc/blob/master/src/cpp/ext/proto_server_reflection.h
Or the orca service, which is implemented as callback API: https://github.com/grpc/grpc/blob/master/src/cpp/server/orca/orca_service.cc

**Comment by nikkov** [comment]
Thanks for the great work! I think this issue can be closed.
