### ISSUE TITLE
None of the methods works for compilation/build

### ISSUE THREAD

**Issue by bharat76** [Tradias/asio-grpc#54]
I am using WSL Ubuntu 20.04.x. I have tried all the possible ways of compiling and building. 
Nothing works. Recent ones is with vcpkg fails with errors.
I can post here hunter and conan errors as well, if that is helpful. 
I am sure, being newbie, I must have missed something. 
 
**CMakeLists.txt**
```
cmake_minimum_required(VERSION 3.16)
project(expr)
add_compile_options(-Wall -ggdb -std=c++14 -pthread)
find_package(asio-grpc CONFIG REQUIRED)
add_executable(boo boo.cpp)
target_link_libraries(boo PUBLIC asio-grpc::asio-grpc)
```

**ERROR**
```
➜  build cmake -DCMAKE_TOOLCHAIN_FILE=/home/bbhushan/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
CMake Error at CMakeLists.txt:4 (find_package):
  Could not find a package configuration file provided by "asio-grpc" with
  any of the following names:

    asio-grpcConfig.cmake
    asio-grpc-config.cmake

  Add the installation prefix of "asio-grpc" to CMAKE_PREFIX_PATH or set
  "asio-grpc_DIR" to a directory containing one of the above files.  If
  "asio-grpc" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/bbhushan/work/expr/build/CMakeFiles/CMakeOutput.log".
```

**vpkg list**
```
➜  vcpkg git:(master) ./vcpkg list | grep "asio\|grpc"
asio-grpc:x64-linux                               2.3.0               Asynchronous gRPC with Asio/unified executors
asio:x64-linux                                    1.24.0              Asio is a cross-platform C++ library for network...
boost-asio:x64-linux                              1.80.0#2            Boost asio module
grpc:x64-linux                                    1.50.1              An RPC library and framework
grpc[codegen]:x64-linux                                               Build code generator machinery
```

**cmake VERSION**
```
➜  vcpkg git:(master) cmake --version
cmake version 3.16.3
```

**Comment by Tradias** [comment]
Thank you for taking the time and provide such a detailed error description.

## Standalone Asio

If you want to use standalone asio then you should change your `target_link_libraries` command:

```cmake
target_link_libraries(boo PUBLIC asio-grpc::asio-grpc-standalone-asio)
```

## Vcpkg

My **recommendation** is to use [vcpkg manifest](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md) files. Add a `vcpkg.json` to the root of your project:

```json
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
    "name": "boo",
    "version": "0.1.0",
    "dependencies": [
        "asio-grpc",
        "asio"
    ]
}
```

then configure your CMake project with the same `CMAKE_TOOLCHAIN_FILE` arg like you did. Vcpkg will automatically build the required dependencies and make them available for `find_package`.

**Alternatively**, you can try running 
```
sudo vcpkg integrate install
```

and then configure CMake again. If this does not work then try adding `-DVCPKG_HOST_TRIPLET=x64-linux` to your CMake command.

## C++ standard

Note that asio-grpc requires C++17, it will automatically at the required command line argument through [target_compile_features](https://cmake.org/cmake/help/latest/command/target_compile_features.html).

**Comment by Tradias** [comment]
You can also check out this example project that uses vcpkg in manifest mode: https://github.com/Tradias/example-vcpkg-grpc/tree/asio-grpc-14

**Comment by bharat76** [comment]
@Tradias Thank you for your guidance.
I will try to collect hunter and conan error during the week and let you know the details.
