### ISSUE TITLE
Clang 14 and 15 build error

### ISSUE THREAD

**Issue by ivan-volnov** [Tradias/asio-grpc#57]
Hello. Thanks for the library!

```
asio-grpc/src/agrpc/detail/memory_resource.hpp:26:10: fatal error: 'memory_resource' file not found
#include <memory_resource>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

I have this include in `#include <experimental/memory_resource>`

**Comment by Tradias** [comment]
When using clang+libc++ you can tell asio-grpc to utilize Boost.Container instead of `<memory_resource>`. See [Usage](https://github.com/Tradias/asio-grpc#usage) in the README. For example, vcpkg with standalone asio would look like this:

```json
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
    "name": "test",
    "version": "0.1.0",
    "dependencies": [
        {
            "name": "asio-grpc",
            "features": [
                "boost-container"
            ]
        },
        "asio"
    ]
}
```

**Comment by ivan-volnov** [comment]
Thanks, I saw it. But I hoped to use it without Boost. Purely with standalone asio. May be add another option for experimental prefix?

**Comment by Tradias** [comment]
Sure, I can look into it. experimental/memory_resource won't work however, because it does not contain [unsynchronized_pool_resource](https://en.cppreference.com/w/cpp/memory/unsynchronized_pool_resource). I could use something like [recycling_allocator](https://www.boost.org/doc/libs/develop/doc/html/boost_asio/reference/recycling_allocator.html) instead.

**Comment by ivan-volnov** [comment]
Yes, you are right, experimental/memory_resource doesn't contain unsynchronized_pool_resource.

Unfortunately recycling_allocator is not a big deal either because of Boost dependency.

Will looking for another workaround.

Tried to update clang to 15. No luck.

The work on memory_resource has been abandoned in clang:
https://quuxplusone.github.io/blog/2018/06/05/libcpp-memory-resource/

**Comment by Tradias** [comment]
Oh the recycling_allocator is part of Asio, which means it is also available in standalone asio: https://think-async.com/Asio/asio-1.24.0/doc/asio/reference/recycling_allocator/recycling_allocator.html

**Comment by ivan-volnov** [comment]
Well, it would be great! Looking forward for the commit =)

**Comment by Tradias** [comment]
Master branch now contains an option to enable the use of recycling_allocator:

```cmake
set(ASIO_GRPC_USE_RECYCLING_ALLOCATOR on)
set(ASIO_GRPC_USE_BOOST_CONTAINER off)

add_subdirectory(/path/to/repository/root)
```

**Comment by Tradias** [comment]
Version 2.4.0 has been released containing this feature. I also simplified it such that

```cmake
set(ASIO_GRPC_USE_RECYCLING_ALLOCATOR on)
add_subdirectory(/path/to/repository/root)
```

should do the trick. Let me know if everything works as you expect.

**Comment by Tradias** [comment]
Hi @ivan-volnov,

have you found some time to test the new feature, does it work as you expect? If so, could you close the issue please?

**Comment by ivan-volnov** [comment]
Hi @Tradias,

Thank you very much for fixing the issue.

I ended up with writing my own small one-file implementation of the library using your old blog post. Thanks a lot for this!

So, I can't test it anymore...
I don't use the code I don't understand or that has a lot of redundant stuff.

My recommendations are: refactor the library, make it small and easy as possible.
