### ISSUE TITLE
Asio-grpc as a subdirectory asio standalone example issue

### ISSUE THREAD

**Issue by ivan-volnov** [Tradias/asio-grpc#58]
Here it is https://github.com/Tradias/asio-grpc#usage

Section: As a subdirectory using standalone Asio:

```cmake
find_package(gRPC)
find_package(asio)
add_subdirectory(/path/to/repository/root)
target_link_libraries(your_app PUBLIC gRPC::grpc++_unsecure asio-grpc::asio-grpc-standalone-asio asio::asio)
```

First of all, no such find_package(asio) in cmake modules. Replaced this line to:
```cmake
# Standalone Asio
find_path(ASIO_INCLUDE_PATH asio.hpp HINTS
    "/usr/include"
    "/usr/local/include"
    "/opt/local/include"
)
if (NOT ASIO_INCLUDE_PATH)
    message(FATAL_ERROR "${Green}No ASIO found${Reset}")
endif()
message(STATUS "${Yellow}Found ASIO${Reset}: ${ASIO_INCLUDE_PATH}")
add_library(asio INTERFACE)
target_include_directories(asio
    INTERFACE ${ASIO_INCLUDE_PATH}
)
target_compile_definitions(asio
    INTERFACE ASIO_STANDALONE
)
```

Then, tried to test option ASIO_GRPC_USE_BOOST_CONTAINER.
Added `-DASIO_GRPC_USE_BOOST_CONTAINER=ON` to cmake call.
Nothing changes. It looks like file `asio-grpc/cmake/AsioGrpcOptionDefaults.cmake` is never execuded.

Please test your library using add_subdirectory() and a pure CMake generate call.

**Comment by Tradias** [comment]
Yes, the find_package calls are just an example, I know that standalone Asio does not provide a CMake config. Your findmodule for it is therefore expected to be provided by the user. I will adjust the readme and remove the find_package calls.

In one of the recent changes which made it possible to copy-paste the src/ directory of asio-grpc and use it without CMake I apparently broke the `ASIO_GRPC_USE_BOOST_CONTAINER` CMake option in `add_subdirectory` mode. Sorry for that. I will attempt to write a unit test for it, just like there is one for asio-grpc's install config. To be honest, I was hoping that no one has to use `add_subdirectory` these days anymore 😟.

**Comment by Tradias** [comment]
Should be fixed on master now.

**Comment by ivan-volnov** [comment]
Thank you for fixing the issue.

> I was hoping that no one has to use add_subdirectory these days anymore

Well, I believe it's quite convenient and rock solid to plug all dependencies via git submodules without any fancy package managers.
