### ISSUE TITLE
how to integrate  agrpc::GrpcContext  with existing asio::io_context  

### ISSUE THREAD

**Issue by RavikumarTulugu** [Tradias/asio-grpc#62]
Thanks for a wonderful library, I was in the process of migration some code to agrpc.
how do I hookup existing boost::asio::io_context  with GrpcContext ?? 
some thing like "boost::asio::posix::stream_descriptor" 
The api is not clear to me. 
Please advise.

**Comment by Tradias** [comment]
I have now tried to summary the possible approaches in this documentation article: https://tradias.github.io/asio-grpc/md_doc_using_asio_io_context.html
I hope that helps, let me know if you have further questions.

**Comment by RavikumarTulugu** [comment]
Thanks for the link.
