### ISSUE TITLE
example share-io-context-client,server.cpp usage

### ISSUE THREAD

**Issue by RavikumarTulugu** [Tradias/asio-grpc#67]
i ran the server and then the client ( share-io-context-client,server).
./server 50051 9000 
./client 50051 9000 
Nothing happens, the server instead of continuing to run, it exits. both client and server donot print anything on console. 
is it expected behavior ?? please advise. 
Thanks

**Comment by Tradias** [comment]
Yes that is expected. Please study the code. The client sends a simple message "example" over tcp (`make_tcp_request`) and a simply unary gRPC request to the server (`make_grpc_request`). After that the io_context runs out of work, resets the grpc_context_work_guard which causes the application to end.
