### ISSUE TITLE
Can I use asio-grpc inside an existing boost::asio application?

### ISSUE THREAD

**Issue by neucer** [Tradias/asio-grpc#90]
I have an existing application started with
```
boost::asio::io_context io_ctx;
boost::asio::co_spawn(io_ctx, asioMain(), boost::asio::detached);
io_ctx.run();
```

Somewhere deep inside `asioMain`, in some coroutine, I want to co_await a grpc request:
```

boost::asio::awaitable<void> TritonClient::someCoroutine() {
    ...
    grpc::Status status = co_await RPC::request(?, stub, client_context, request, response, asio::use_awaitable);
    ...
}
```

Is that even possible? Do I still need to create a `agrpc::GrpcContext`? Do I run it? I don't know where to start.

**Comment by Tradias** [comment]
I tried to outline your options in the documentation: https://tradias.github.io/asio-grpc/md_doc_using_asio_io_context.html

I recommend going for the **Explicitly constructed io_context** and **Run on separate threads** approach.

**Comment by neucer** [comment]
If I run it on a separate thread, all my code will still run on the same thread (`io_context`'s thread). Is that correct? And only some internal agrpc will run on the other thread, right?

Thank you for your help.

**Comment by Tradias** [comment]
For `co_spawn`+`asio::use_awaitable` that is correct. Technically it depends on the completion handler executor, some details here: https://github.com/Tradias/asio-grpc/issues/88#issuecomment-1812364613

In your case you can also use the slightly more performant [GrpcContext.run_completion_queue](https://tradias.github.io/asio-grpc/classagrpc_1_1_grpc_context.html#a627dcc6bc3401d204d976b6fea6e00a3) function.

**Comment by neucer** [comment]
I expected it to be like `io_context`, but that would be nice too.
So if I use a different `GrpcContext` but the same `stub`, would that be thread safe?
