### ISSUE TITLE
build fails with latest boost 1.84 

### ISSUE THREAD

**Issue by RavikumarTulugu** [Tradias/asio-grpc#93]
Please check build with latest boost 1.84 as some headers are replaced or removed.

**Comment by Tradias** [comment]
This should be fixed in 2.9.0

**Comment by RavikumarTulugu** [comment]
I tested with 2.9.1 and got some missing header error under boost asio folder.

**Comment by Tradias** [comment]
I had already addressed this issue but overlooked one boost.asio header in the test (only removed the standalone asio version of it). Removing it makes everything compile fine. Also your code should never have been affected to begin with. Are you compiling all tests of asio-grpc?

**Comment by RavikumarTulugu** [comment]
fixed in 2.9.3
