### ISSUE TITLE
How to make grPC Client to Establish connection based on IP address?

### ISSUE THREAD

**Issue by vtharmalingam** [Tradias/asio-grpc#98]
Hi @Tradias: 

I'm attempting to execute the client from a remote machine. However, despite setting the Server IP in the provided code (below) and ensuring it's configured with the 'InsecureChannelCredentials' option, the connection isn't established. I also observed that your "helloworld" client is configured exclusively with "localhost".

```cpp
    const auto host = "<IP>:" + cfg.getGrpcPort(); 
    grpc::Status status;
    helloworld::Greeter::Stub stub{grpc::CreateChannel(host, grpc::InsecureChannelCredentials())};
```

Could you kindly direct me to a sample client code that connects to a server without SSL enabled or with minimal settings regarding SSL, specifically utilizing the ChannelCredentials option? This is one of my limitations in testing the framework in a real production use case...

Thanks for your help!

Thanks,
Tharma

**Comment by Tradias** [comment]
Hi, I personally only ever used hostname based address, for example in docker-compose or k8s deployments. I did however have issues with IP address clients on Windows (e.g. using 127.0.0.1) in the past but not anymore (not sure when it changed but gRPC 1.51.1+ seems to work). Again this does not look like an asio-grpc question :), if you continue to have issues you might want to open an issue on gRPC.

You can also check the state of the channel before starting an RPC and asking it to establish a connection to the server by using:

```c++
    const auto channel = grpc::CreateChannel(host, grpc::InsecureChannelCredentials());
    const auto state = channel->GetState(true);
    while (GRPC_CHANNEL_READY != state && GRPC_CHANNEL_TRANSIENT_FAILURE != state) {
    const auto deadline = std::chrono::system_clock::now() + std::chrono::seconds(5);
    bool has_state_changed =
        co_await agrpc::notify_on_state_change(grpc_context, *channel, state, deadline, asio::use_awaitable);
    }
```

**Comment by vtharmalingam** [comment]
Thank you for the quick response, @Tradias. This is helpful. Sure, will check with the gRPC team.

Regards,
Tharma
